import type { Metadata } from 'next';
import './globals.css';

import { ThemeProvider } from 'next-themes';
import { Inter } from 'next/font/google';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SpeedInsights />
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="fixed inset-0 flex items-center justify-center bg-blue-100">
            <div className="bg-white shadow-xl rounded-xl w-2/3 h-2/3 min-w-[650px] min-h-[600px] overflow-hidden">
              {children}
            </div>
          </div>
          <Toaster position="top-center" reverseOrder={false} />
        </ThemeProvider>
      </body>
    </html>
  );
}
